"""
Django settings for FarmSetu project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from django.db.models import Sum, Avg

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l&qwx##z+feeeu3!e(po7pgv=$m6j22t+8@v1_ph4tfz!tj1d_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework.apps.RestFrameworkConfig',
    'weather.apps.WeatherConfig',
]

MIDDLEWARE = [
    'log_request_id.middleware.RequestIDMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FarmSetu.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FarmSetu.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = 'media/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOG_LEVEL = "DEBUG"

APP_LOG_FILE = os.path.join(BASE_DIR, 'FarmSetu', 'application_logs.log')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        "request_id": {
            "()": "log_request_id.filters.RequestIDFilter"
        }
    },
    'formatters': {
        "verbose": {
            "format": "%(asctime)s.%(msecs)03d | %(thread)d | %(levelname)s | %(module)s | %(name)s | %(request_id)s "
                      "| %(message)s",
            "datefmt": '%Y-%m-%dT%H:%M:%S',
        }
    },

    'handlers': {
        'console': {
            'level': LOG_LEVEL,
            'filters': ['request_id', 'require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },

        'app_file': {
            'level': LOG_LEVEL,
            'filters': ['request_id'],
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': APP_LOG_FILE,
            'maxBytes': 16777216,
            'formatter': 'verbose',
            'backupCount': 200,
        },
    },

    'loggers': {
        'django.db.backends': {
            'level': LOG_LEVEL,
            'handlers': ['console'],
         },

        '': {
            'handlers': ['app_file'],
            'level': LOG_LEVEL,
        },

        'weather': {
            'handlers': ['app_file'],
            'level': LOG_LEVEL,
        },
    }
}

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 30
}

WEATHER_URL = "https://www.metoffice.gov.uk/pub/data/weather/uk/climate/datasets/<weather_parameter>/date/<region>.txt"

ANNOTATE_SUM_COLUMN_MAPPING = {'jan': ('jan_sum', Sum('jan')), 'feb': ('feb_sum', Sum('feb')),
                               'mar': ('mar_sum', Sum('mar')), 'apr': ('apr_sum', Sum('apr')),
                               'may': ('may_sum', Sum('may')), 'jun': ('jun_sum', Sum('jun')),
                               'jul': ('jul_sum', Sum('jul')), 'aug': ('aug_sum', Sum('aug')),
                               'sep': ('sep_sum', Sum('sep')), 'oct': ('oct_sum', Sum('oct')),
                               'nov': ('nov_sum', Sum('nov')), 'dec': ('dec_sum', Sum('dec')),
                               'ann': ('ann_sum', Sum('ann')), 'aut': ('aut_sum', Sum('aut')),
                               'spr': ('spr_sum', Sum('spr')), 'win': ('win_sum', Sum('win'))}

ANNOTATE_AVG_COLUMN_MAPPING = {'jan': ('jan_avg', Avg('jan')), 'feb': ('feb_avg', Avg('feb')),
                               'mar': ('mar_avg', Avg('mar')), 'apr': ('apr_avg', Avg('apr')),
                               'may': ('may_avg', Avg('may')), 'jun': ('jun_avg', Avg('jun')),
                               'jul': ('jul_avg', Avg('jul')), 'aug': ('aug_avg', Avg('aug')),
                               'sep': ('sep_avg', Avg('sep')), 'oct': ('oct_avg', Avg('oct')),
                               'nov': ('nov_avg', Avg('nov')), 'dec': ('dec_avg', Avg('dec')),
                               'ann': ('ann_avg', Avg('ann')), 'aut': ('aut_avg', Avg('aut')),
                               'spr': ('spr_avg', Avg('spr')), 'win': ('win_avg', Avg('win'))}
