# Generated by Django 4.2.2 on 2023-06-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('weather_parameter', models.CharField(max_length=50)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('jan', models.FloatField(blank=True, max_length=20, null=True)),
                ('feb', models.FloatField(blank=True, max_length=20, null=True)),
                ('mar', models.FloatField(blank=True, max_length=20, null=True)),
                ('apr', models.FloatField(blank=True, max_length=20, null=True)),
                ('may', models.FloatField(blank=True, max_length=20, null=True)),
                ('jun', models.FloatField(blank=True, max_length=20, null=True)),
                ('aug', models.FloatField(blank=True, max_length=20, null=True)),
                ('sep', models.FloatField(blank=True, max_length=20, null=True)),
                ('oct', models.FloatField(blank=True, max_length=20, null=True)),
                ('nov', models.FloatField(blank=True, max_length=20, null=True)),
                ('dec', models.FloatField(blank=True, max_length=20, null=True)),
                ('winter', models.FloatField(blank=True, max_length=20, null=True)),
                ('spring', models.FloatField(blank=True, max_length=20, null=True)),
                ('summer', models.FloatField(blank=True, max_length=20, null=True)),
                ('autumn', models.FloatField(blank=True, max_length=20, null=True)),
                ('annual', models.FloatField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
